apiVersion : apps/v1
kind: Deployment
metadata:
  name: racatapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: racatapp
  template:
    metadata:
      labels:
        app: racatapp 
    spec:
      containers:
        - name: racatapp 
          image: azurecontaineraks.azurecr.io/custom2aksnginxapp1:8a908870d4bb0894c036bc56691d8fe3f8fc3937
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: racatapp
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: racatapp
